services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: chatwoot-growfik-v3:latest
    env_file: .env
    volumes:
      - storage_data_v2:/app/storage

  migrations:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: bundle exec rails db:migrate
    restart: on-failure

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
      - migrations
    ports:
      - '0.0.0.0:3010:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
      - migrations
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '127.0.0.1:5544:5432'
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_v2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pg_Str0ng_Chatwoot_2026

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"Rd_Str0ng_Chatwoot_2026\""]
    volumes:
      - redis_data_v2:/data
    ports:
      - '127.0.0.1:6390:6379'

volumes:
  storage_data_v2:
  postgres_data_v2:
  redis_data_v2:
